# Generated by Django 3.0.3 on 2020-08-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaznici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('telefon', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ipv4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresa', models.IntegerField()),
                ('aktivni', models.CharField(max_length=1)),
                ('id_zakaznika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakaznici.Zakaznici')),
            ],
        ),
    ]
