# Generated by Django 3.0.3 on 2020-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipv4',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
