# Generated by Django 3.0.3 on 2020-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0002_ipv4_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4',
            name='aktivni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipv4',
            name='ip_adresa',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
