# Generated by Django 3.0.3 on 2020-09-21 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0003_IPv4_model_zmena_typu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='telefon',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Zadejte telefon ve formatu +420123456789 nebo 123456789.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
