# Generated by Django 3.0.3 on 2020-09-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0005_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipv6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.GenericIPAddressField(protocol='IPv6')),
                ('maska', models.PositiveSmallIntegerField()),
                ('aktivni', models.BooleanField(default=False)),
                ('id_zakaznika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.Zakaznici')),
            ],
        ),
    ]
