# Generated by Django 3.0.3 on 2020-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0006_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv6',
            name='maska',
            field=models.PositiveSmallIntegerField(default=56),
        ),
    ]
