# Generated by Django 3.0.3 on 2020-10-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0007_ipv6_maska_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifniSkupiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=50)),
                ('cena', models.PositiveSmallIntegerField()),
                ('rychlost_down', models.PositiveIntegerField()),
                ('rychlost_up', models.PositiveIntegerField()),
                ('id_tarifniskupiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp.TarifniSkupiny')),
            ],
        ),
        migrations.CreateModel(
            name='Adresy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_obce', models.CharField(max_length=50)),
                ('nazev_ulice', models.CharField(max_length=50)),
                ('cislo_domovni', models.PositiveSmallIntegerField()),
                ('psc', models.PositiveIntegerField()),
                ('id_tarifniskupiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isp.TarifniSkupiny')),
            ],
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='id_adresy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Adresy'),
        ),
        migrations.AddField(
            model_name='zakaznici',
            name='id_tarifu',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Tarify'),
        ),
    ]
