# Generated by Django 3.0.3 on 2020-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0009_IPV4_bez_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
