# Generated by Django 3.0.3 on 2021-01-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0010_zakaznici_email_nepovinny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaznici',
            name='id_adresy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Adresy'),
        ),
        migrations.AlterField(
            model_name='zakaznici',
            name='id_tarifu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Tarify'),
        ),
    ]
