# Generated by Django 3.0.3 on 2021-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0011_Zakaznici_ID_adresy_a_tarifu_mozno_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4',
            name='aktivni',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ipv6',
            name='aktivni',
            field=models.BooleanField(default=True),
        ),
    ]
