# Generated by Django 3.0.3 on 2021-01-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isp', '0012_IP_defaultne_aktivni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipv4',
            name='ip_adresa',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 adresa'),
        ),
        migrations.AlterField(
            model_name='zakaznici',
            name='id_adresy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Adresy', verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='zakaznici',
            name='id_tarifu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='isp.Tarify', verbose_name='Tarif'),
        ),
    ]
